[OBEY-CAMPAIGN-8deed8b4-FE-CH0001] fix: make shell navigation transparent

diff --git a/internal/shell/templates/bash.sh.tmpl b/internal/shell/templates/bash.sh.tmpl
--- a/internal/shell/templates/bash.sh.tmpl
+++ b/internal/shell/templates/bash.sh.tmpl
@@ -13,26 +13,64 @@ camp() {
   case "$1" in
     switch|sw)
       shift
+      local arg passthrough status
+      passthrough=0
+      for arg in "$@"; do
+        case "$arg" in
+          --help|-h|--json|--json=*|--print|--print=*)
+            passthrough=1
+            break
+            ;;
+        esac
+      done
+      if [ "$passthrough" -eq 1 ]; then
+        command camp switch "$@"
+        return
+      fi
       dest=$(command camp switch "$@" --print)
+      status=$?
       if [ -n "$dest" ]; then
         cd "$dest" || return 1
+      elif [ "$status" -ne 0 ]; then
+        return "$status"
+      else
+        echo "camp: not found: $*" >&2
+        return 1
       fi
       ;;
     go|g)
       shift
+      local arg passthrough status
+      passthrough=0
+      for arg in "$@"; do
+        case "$arg" in
+          --help|-h|--json|--json=*|--print|--print=*)
+            passthrough=1
+            break
+            ;;
+        esac
+      done
+      if [ "$passthrough" -eq 1 ]; then
+        command camp go "$@"
+        return
+      fi
       if [ $# -eq 0 ]; then
-        dest=$(command camp go --print 2>/dev/null)
+        dest=$(command camp go --print)
+        status=$?
         if [ -n "$dest" ]; then
           cd "$dest" || return 1
+        elif [ "$status" -ne 0 ]; then
+          return "$status"
         fi
-      elif [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
-        command camp go --help
       elif [ "$1" = "-c" ]; then
         command camp go "$@"
       else
-        dest=$(command camp go "$@" --print 2>/dev/null)
+        dest=$(command camp go "$@" --print)
+        status=$?
         if [ -n "$dest" ]; then
           cd "$dest" || return 1
+        elif [ "$status" -ne 0 ]; then
+          return "$status"
         else
           echo "camp: not found: $*" >&2
           return 1
diff --git a/internal/shell/templates/fish.sh.tmpl b/internal/shell/templates/fish.sh.tmpl
--- a/internal/shell/templates/fish.sh.tmpl
+++ b/internal/shell/templates/fish.sh.tmpl
@@ -32,25 +32,59 @@ function camp --description "Camp CLI wrapper with directory-changing support"
     switch "$argv[1]"
         case switch sw
             set -l rest $argv[2..-1]
+            set -l passthrough 0
+            for arg in $rest
+                switch "$arg"
+                    case --help -h --json '--json=*' --print '--print=*'
+                        set passthrough 1
+                        break
+                end
+            end
+            if test "$passthrough" -eq 1
+                command camp switch $rest
+                return $status
+            end
             set -l dest (command camp switch $rest --print)
+            set -l cmd_status $status
             if test -n "$dest"
                 cd $dest
+            else if test "$cmd_status" -ne 0
+                return $cmd_status
+            else
+                echo "camp: not found: $rest" >&2
+                return 1
             end
         case go g
             set -l rest $argv[2..-1]
+            set -l passthrough 0
+            for arg in $rest
+                switch "$arg"
+                    case --help -h --json '--json=*' --print '--print=*'
+                        set passthrough 1
+                        break
+                end
+            end
+            if test "$passthrough" -eq 1
+                command camp go $rest
+                return $status
+            end
             if test (count $rest) -eq 0
-                set -l dest (command camp go --print 2>/dev/null)
+                set -l dest (command camp go --print)
+                set -l cmd_status $status
                 if test -n "$dest"
                     cd $dest
+                else if test "$cmd_status" -ne 0
+                    return $cmd_status
                 end
-            else if test "$rest[1]" = "--help" -o "$rest[1]" = "-h"
-                command camp go --help
             else if test "$rest[1]" = "-c"
                 command camp go $rest
             else
-                set -l dest (command camp go $rest --print 2>/dev/null)
+                set -l dest (command camp go $rest --print)
+                set -l cmd_status $status
                 if test -n "$dest"
                     cd $dest
+                else if test "$cmd_status" -ne 0
+                    return $cmd_status
                 else
                     echo "camp: not found: $rest" >&2
                     return 1
